# Generated by Django 3.1.7 on 2021-03-23 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managers_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
