# Generated by Django 3.1.7 on 2021-03-24 07:30

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/dk/PycharmProjects/digital_marketplace/static_cdn/protected'), upload_to=products.models.download_media_location),
        ),
    ]
