# Generated by Django 3.1.7 on 2021-03-28 13:37

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210328_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/dk/PycharmProjects/digital_marketplace/static_cdn/protected'), upload_to=products.models.download_media_location),
        ),
    ]
